- hosts: servera
  tasks:
  - yum:
      name: 
      - php
      - mariadb 
      state: present
    

  - yum:
      name: '@RPM Development Tools' 
      state: present
   

  - yum:
      name: '*'
      state: latest 
     

